Use AC_CONFIG_HEADERS instead of AM_CONFIG_HEADER in configure.in
This fixes the following error with automake 1.13.

error: 'AM_CONFIG_HEADER': this macro is obsolete.
You should use the 'AC_CONFIG_HEADERS' macro instead.